"use client";

import type { Metadata } from "next";
import './globals.css';
import { Box, createTheme, CssBaseline, ThemeProvider } from "@mui/material";

const blackJackTheme = createTheme({
  palette: {
    mode: "dark",
    primary: {
      main: "#ffd700",
    },
    secondary: {
      main: "#ffd700",
    },
    background: {
      default: "#013220", // Dark green background for the whole app
    },
  },
  components: {
    MuiCard: {
      styleOverrides: {
        root: {
          backgroundColor: "#ffffff", // White background for Card
          color: "#000000", // Black text for Card
        },
      },
    },
  }
});

const lightTheme = createTheme({
  palette: {
    mode: "light", // Default mode
    primary: {
      main: "#1976d2", // Customize primary color
    },
    secondary: {
      main: "#dc004e", // Customize secondary color
    },
  },
});

const darkTheme = createTheme({
  palette: {
    mode: "dark", // Dark theme
    primary: {
      main: "#90caf9", // Lighter primary for dark mode
    },
    secondary: {
      main: "#f48fb1", // Lighter secondary for dark mode
    },
  },
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={blackJackTheme}>
          <CssBaseline />
          <Box height="100vh" width="100vw" >
            {children}
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
