import type { Metadata } from "next";
import "./globals.css";
import { createTheme, ThemeProvider } from "@mui/material/styles";
import { Box } from "@mui/material";

const theme = createTheme({
  palette: {
    primary: {
      main: "#35654d",
    },
    secondary: {
      main: "#0f0",
    },
  },
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider theme={theme}>
          <Box height="100vh" width="100vw">
            {children}
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
}
